language: ruby
sudo: required
dist: trusty
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --retry=3
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby-19mode
  - rbx-3
  - ruby-head
matrix:
  allow_failures:
  - rvm: rbx-3
  - rvm: ruby-head
  - rvm: jruby-19mode
addons:
  apt:
    packages:
      - haveged
